### ISSUE TITLE
Upgrade to H2 1.4.200

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-h2#114]
https://github.com/h2database/h2database/releases/tag/version-1.4.200

**Comment by lhotari** [comment]
Any plans to release with this change?

Spring Boot upgraded to 1.4.200 in this commit: https://github.com/spring-projects/spring-boot/commit/b60549d6ca7a4d445f65886364e7bcf8e1ea0b2d and together with R2DBC 0.8.0.RC2 I get an error:
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.h2.engine.Constants.getVersion()'
	at io.r2dbc.h2.H2Connection.<init>(H2Connection.java:67)
	at io.r2dbc.h2.H2ConnectionFactory.lambda$create$1(H2ConnectionFactory.java:130)
``` 
I did find a workaround so this is not currently urgent, but others might stumble upon the same issue so here's the workaround (for gradle):
 ```
  ext['h2.version'] = '1.4.199'
```

**Comment by mp911de** [comment]
Yes, we're going to ship 0.8.0.RELEASE in about 2 weeks.
