### ISSUE TITLE
R2DBC - Oracle Database Support

### ISSUE THREAD

**Issue by cantetik** [r2dbc/r2dbc-h2#121]
I found R2DBC when I was searching reactive relational database drivers, but I couldn't see any driver for Oracle DB. Does anyone have any information on whether to provide support?

**Comment by mp911de** [comment]
There’s no Oracle driver that implements R2DBC. Oracle announced during Code One ojdbc20 exposing API that looks heavily inspired by R2DBC. From that perspective, one could wait for ojdbc20 to be published and write a R2DBC wrapper.
