### ISSUE TITLE
Add Enum codec

### ISSUE THREAD

**Issue by pull-vert** [r2dbc/r2dbc-h2#131]
see http://h2database.com/html/datatypes.html#enum_type

**Comment by katzyn** [comment]
Please note that documentation is not correct, the `ENUM` values are actually returned as `java.lang.String` values in JDBC in recent versions of H2, and you also shouldn't rely on 0-based ordinal numbers, their numbering is a subject to change.

**Comment by mp911de** [comment]
Thanks for the proposal. We decided to not add support for `enum` types across R2DBC drivers as the mapping of Java enum's is not uniquely defined, one can use `String` or ordinals (see r2dbc/r2dbc-mssql#33, r2dbc/r2dbc-mssql#34, r2dbc/r2dbc-postgresql#103)

**Comment by pull-vert** [comment]
understood, thanks for the explanation

**Comment by JohnNiang** [comment]
Hi @mp911de , I found PostgreSQL driver has already supported `Enum` codec, please refer to <https://github.com/pgjdbc/r2dbc-postgresql/issues/244#issuecomment-635962753>.

I would be great if we reopened this issue.
