### ISSUE TITLE
Can't connect to h2 db

### ISSUE THREAD

**Issue by DmitryYusupov** [r2dbc/r2dbc-h2#15]
`H2ConnectionFactory.class` ->
```
private static ConnectionInfo getConnectionInfo(H2ConnectionConfiguration configuration)
```

I don't understand , why you append `:` to the end of builder!? 
```
StringBuilder sb = new StringBuilder(START_URL).append(configuration.getUrl()).append(":");
```

So, i always get an error like this

```
Failed to obtain R2DBC Connection; nested exception is org.h2.message.DbException: A file path that is implicitly relative to the current working directory is not allowed in the database URL \"jdbc:h2:/~testdb:;USER=sa\". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-197]
```
 
`jdbc:h2:/~testdb:`  is not correct, but `jdbc:h2:/~testdb` is correct

**Comment by gregturn** [comment]
`/~testdb` cannot be a valid pathname. `~` is a shortcut to your personal homedir. Prefixing it with the root path is a conflict.

**Comment by gregturn** [comment]
If you could paste your entire configuration code that would help.

**Comment by DmitryYusupov** [comment]
Ok. when i open my sql editor i find my db and isee that it has url **jdbc:h2:~/testdb**

I want to create such url with H2ConnectionConfiguration

```
    @Bean
    @Profile(value = ["test"])
    fun h2ConnectionFactory(): H2ConnectionFactory {
        val builder = H2ConnectionConfiguration.builder()
        val config = with(databaseProps) {
            builder.url("/~testdb").username("sa").build()
        }
        return H2ConnectionFactory(config)
    }

```

So  public static final String START_URL = "jdbc:h2:";

All i need -is to append `/~testdb`. But it also appends ":" to the end

`StringBuilder sb = new StringBuilder(START_URL).append(configuration.getUrl()).append(":");`

**Comment by DmitryYusupov** [comment]
Ok, thanks.

**Comment by DmitryYusupov** [comment]
Relly, look at this

```
@Bean
@Profile(value = ["test"])
fun h2ConnectionFactory(): H2ConnectionFactory {
    val builder = H2ConnectionConfiguration.builder()
    val config = with(databaseProps) {
        builder.url("jdbc:h2:tcp://localhost/~/test").username("sa").build()
    }
    return H2ConnectionFactory(config)
}
```

**Comment by nebhale** [comment]
We have effectively the same implementation with the one caveat that you shouldn't put in `jdbc:h2:` since this isn't JDBC 😄
