### ISSUE TITLE
Add Interval Codecs

### ISSUE THREAD

**Issue by TheNumberOne** [r2dbc/r2dbc-h2#159]
#### Is your feature request related to a problem? Please describe

Currently, this driver cannot decode any of H2's Interval values.

#### Describe the solution you'd like

Add support for the Interval types 

- intervalYearType
- intervalMonthType
- intervalDayType
- intervalHourType
- intervalMinuteType
- intervalSecondType
- intervalYearToMonthType
- intervalDayToHourType
- intervalDayToMinuteType
- intervalDayToSecondType
- intervalHourToMinuteType
- intervalHourToSecondType
- intervalMinuteToSecondType

In addition to converting to org.h2.api.Interval objects, add support for converting to the java.time.Period and java.time.Duration objects to the appropriate interval types.

#### Describe alternatives you've considered

Current alternatives include storing items using varchar into the database. However, this reduces the features of H2 available for use. 

#### Teachability, Documentation, Adoption, Migration Strategy

This can be done by implementing Codecs corresponding to each one of these conversions.

**Comment by TheNumberOne** [comment]
Also, is this project still actively developed?

**Comment by mp911de** [comment]
Thanks for your request. This project has little traffic as most features are already in place. 

Feel free to come up with a pull request. Adding codecs for database-specific types makes sense.

**Comment by TheNumberOne** [comment]
Which branch should the pull request be based off of?

**Comment by katzyn** [comment]
> Adding codecs for database-specific types

`INTERVAL` data type is a part of optional feature F052 “Intervals and datetime arithmetic”
from the SQL Standard, even archaic SQL-92 has this data type. It isn't database-specific.

**Comment by mp911de** [comment]
Thanks a lot. We would include this feature with the 0.8.x line.

**Comment by TheNumberOne** [comment]
No probs lol.

**Comment by gregturn** [comment]
Merged to both `0.8.x` and `master`.

**Comment by gregturn** [comment]
Thanks @TheNumberOne !
