### ISSUE TITLE
java.lang.AbstractMethodError: io.r2dbc.h2.H2Statement.executeReturningGeneratedKeys()Lorg/reactivestreams/Publisher;

### ISSUE THREAD

**Issue by lukaseder** [r2dbc/r2dbc-h2#18]
The current version does not seem to implement r2dbc-spi-1.0.0.M5's `io.r2dbc.spi.Statement.executeReturningGeneratedKeys()` method. See the SPI feature for reference: https://github.com/r2dbc/r2dbc-spi/issues/17

**Comment by mp911de** [comment]
The current version of SPI and H2 are 1.0.0.M6. We decided to remove `executeReturningGeneratedKeys()` as this method was basically abstracting dialect-specific SQL. Care to upgrade to 1.0.0 M6?

**Comment by lukaseder** [comment]
OK, sure, thanks for the feedback. That's why I was on M5:

- https://github.com/r2dbc/r2dbc-spi/pull/21
- https://github.com/r2dbc/r2dbc-client/pull/26
