### ISSUE TITLE
Tests don't run on Windows

### ISSUE THREAD

**Issue by lukaseder** [r2dbc/r2dbc-h2#192]
#### Versions

- Driver: 0.8.4.RELEASE
- SPI: 0.9.0.M1
- Database: 1.4.200
- Java: openjdk version "11.0.9.1" 2020-11-04
- OS: Microsoft Windows [Version 10.0.19042.867]

#### Current Behavior

Tests fail on windows
 
#### Steps to reproduce

Check out this project on a windows machine, run `mvn clean install` and see the tests fail. This is the summary output:

```
[ERROR] Failures:
[ERROR]   H2ConnectionFactoryTest.createFileBasedDatabase:66 expectation "expectNextCount(1)" failed (expected: count = 1; actual: counted = 0; signal: onError(io.r2dbc.spi.R2dbcNonTransientResourceException: [90011] [90011] Ein implizit relativer Pfad zum Arbeitsverzeichnis ist nicht erlaubt in der Datenbank URL "jdbc:h2:file:/tmp/test;USER=sa;PASSWORD=". Bitte absolute Pfade, ~/name, ./name, oder baseDir verwenden.
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:/tmp/test;USER=sa;PASSWORD=". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-200]))
[ERROR]   H2RemoteAccessTest.tcpByUrlWorks:58 expectation "expectNextCount(1)" failed (expected: count = 1; actual: counted = 0; signal: onError(io.r2dbc.spi.R2dbcNonTransientResourceException: [90011] [90011] Ein implizit relativer Pfad zum Arbeitsverzeichnis ist nicht erlaubt in der Datenbank URL "jdbc:h2:tcp://localhost:9123//tmp/test;USER=sa;PASSWORD=". Bitte absolute Pfade, ~/name, ./name, oder baseDir verwenden.
A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:tcp://localhost:9123//tmp/test;USER=sa;PASSWORD=". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-200]))
[ERROR] Errors:
[ERROR]   H2RemoteAccessTest.tcpWithHostnameAndPortWorks:66 » FileSystem C:\Users\lukas\...
[ERROR]   H2RemoteAccessTest.tcpWithHostnameButNoPortWorks:93 » FileSystem C:\Users\luka...
[INFO]
[ERROR] Tests run: 264, Failures: 2, Errors: 2, Skipped: 8
```

In a related issue, I tried quite a bit to work around this limitation by tampering with the r2dbc connection URL until I got something working:
https://github.com/r2dbc/r2dbc-h2/issues/188#issuecomment-811332868

Independently of any flaws that may be present in the connection URLs, the tests of this project should run on Windows, too

**Comment by katzyn** [comment]
`jdbc:h2:/C:/path/to/database` is not a valid JDBC URL for H2 on Windows, `jdbc:h2:C:/path/to/database` should be used without an unexpected `/` before the actual path. Exotic `jdbc:h2:/path/to/database` can also be used, this is an absolute path from the root of the current drive (`C:` or other).

**Comment by gregturn** [comment]
Thanks @katzyn. 

@lukaseder: I've amended our test cases to use Java's tempDirectory() APIs to avoid running into this on our own unit tests. I will also investigate with @mp911de the option to expand our r2dbc CI (github actions) to potentially ALSO run test suites on more than just Ubuntu.

@snicoll: I will next investigate the unit tests on Spring Boot to ensure things run smoothly over there as well.
