### ISSUE TITLE
Support for H2 V>2.1.2100

### ISSUE THREAD

**Issue by tamflux** [r2dbc/r2dbc-h2#220]
H2 version <2.1.2100 exposes 3 major security issues. Thus I have to update to version 2.1.2100.
Unfortunately, the r2dbc-h2 driver does not support this version. This exception occurs:

java.lang.NoSuchMethodError: 'void org.h2.engine.ConnectionInfo.<init>(java.lang.String, java.util.Properties)'

**Comment by gregturn** [comment]
To clarify, the `main` branch (R2DBC SPI 0.9.x) supports H2 `2.x`.

The `0.8.x` branch supports the prior spec (R2DBC SPI 0.8.x) and retains support of H2 `1.x`.
