### ISSUE TITLE
Cannot use column label(alias)

### ISSUE THREAD

**Issue by kazuki43zoo** [r2dbc/r2dbc-h2#43]
I used the column label(alias) using "as" clause, it throws an `IllegalArgumentException`.
Is specification this behavior?

e.g.

```java
R2dbc r2dbc = new R2dbc(connectionFactory);
r2dbc.useHandle(h -> h.select("SELECT id as value FROM users ORDER BY id")
    .mapResult(result -> result.map((row, rowMetadata) -> row.get("value"))
  )).subscribe(System.out::println);
```

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: Column name 'VALUE' does not exist in column names [ID]

Caused by: java.lang.IllegalArgumentException: Column name 'VALUE' does not exist in column names [ID]
	at io.r2dbc.h2.H2Row.getColumn(H2Row.java:117)
	at io.r2dbc.h2.H2Row.get(H2Row.java:72)
	at io.r2dbc.spi.Row.get(Row.java:46)
...
```

I hope to use column label(alias).

**Comment by mp911de** [comment]
Column aliasing in the select expression is supported as per the [H2 documentation](http://www.h2database.com/html/grammar.html#select_expression). I'd consider this one a bug in our driver.

**Comment by uaihebert** [comment]
pr is created. ( :

**Comment by gregturn** [comment]
Resolved via https://github.com/r2dbc/r2dbc-h2/commit/4097cb8b4a78e4a794d78ad0715c33bf1f553c07.
