### ISSUE TITLE
Accept bind query param with integer index

### ISSUE THREAD

**Issue by uaihebert** [r2dbc/r2dbc-h2#45]
## Current scenario

Right now, it is only possible to receive String as bind param:
https://github.com/r2dbc/r2dbc-h2/blob/84c0b910a6e75514fcbd4b4014e073bb0f0cccf9/src/main/java/io/r2dbc/h2/H2Statement.java#L68-L73

This code accept as valid input:
- `bind("?1", 100)`
- `bind("$1", 100)`

## What we need to improve
We should support integers as bind params, like:
- `bind(0, 100)`

## Requirements are:

- [ ] update the bind method to support string or integer
- [ ] update the method `getIndex` to support both approaches (https://github.com/r2dbc/r2dbc-h2/blob/84c0b910a6e75514fcbd4b4014e073bb0f0cccf9/src/main/java/io/r2dbc/h2/H2Statement.java#L146)
- [ ] update the read-me and mention that integer is also allowed (https://github.com/r2dbc/r2dbc-h2/blob/84c0b910a6e75514fcbd4b4014e073bb0f0cccf9/README.adoc#programmatic)
- [ ] add tests that covers an input bind param as integer

**Comment by mp911de** [comment]
Great ticket description 👍

**Comment by uaihebert** [comment]
thank you! :D

**Comment by gregturn** [comment]
#44 has been merged so this should free you up to work on this one.

**Comment by uaihebert** [comment]
hey, good to know. the pr for this one is already created! :D

**Comment by uaihebert** [comment]
ops, just now I noticed the conflict

**Comment by uaihebert** [comment]
all done. conflict solved. ( :

**Comment by gregturn** [comment]
Resolved viahttps://github.com/r2dbc/r2dbc-h2/commit/e1d498f1d8206071c2cf3bcf95a660b0565bf6c3.

**Comment by gregturn** [comment]
Thanks @uaihebert!
