### ISSUE TITLE
Migrate from "$1" Postgres notation toward "?" H2 notation for SQL and binding.

### ISSUE THREAD

**Issue by gregturn** [r2dbc/r2dbc-h2#7]
H2 supports "$1" statements in SQL queries and uses positional binding.

Since the SPI Example test now supports multiple paradigms, migrate toward that example. (Or consider supporting BOTH versions!)

**Comment by gregturn** [comment]
But should we support existing users already using `?` for H2?

H2 supports both so we could potentially accept both if it doesn’t break anything.

**Comment by nebhale** [comment]
@mp911de It is more expressive, but it only exists within H2 as part of its PostgreSQL compatibility work.  H2's "native" (for lack of a better term) syntax is JDBC's syntax owing to its inception as a JDBC-aligned project.  It should not be hard to support both, so that's what we'll do.

**Comment by mp911de** [comment]
Wasn't aware of the compatibility mode constraint.

**Comment by uaihebert** [comment]
Hello, the rookie is here. ( :

I prepared this small PR to add this feature, in case of it is really needed.

my 2 cents here: if h2 supports it, why don't we?

**Comment by nebhale** [comment]
@uaihebert I think both can be supported, but `$#` is really a PostgreSQL compatibility notation, not the H2 "native" notation.

**Comment by uaihebert** [comment]
I got your point!

This PR makes the native supported and, because of it, an update on docs will be required. :D

Should I update all the tests and change from `$` to `?`? Or just the README is fine?

**Comment by gregturn** [comment]
We’re actually shooting to have modes of support so don’t replace anything. Instead we can make it an option.

**Comment by gregturn** [comment]
Resolved via https://github.com/r2dbc/r2dbc-h2/commit/70aa32e431d4012340848777d73640e75459e053 and it's implementation of SPI's `Example` TCK using `?#`.

**Comment by gregturn** [comment]
NOTE: The native format is illustrated here => https://github.com/r2dbc/r2dbc-h2/commit/062f47bca04c340d595295842585109d6317ec81.
