### ISSUE TITLE
Decoding a null date value fails with NPE

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-h2#78]
Setup:

```sql
CREATE TABLE IF NOT EXISTS PERSON (
  ID            BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BIRTHDATE     DATE
);

INSERT INTO Person(ID)            VALUES (1);
```

Consuming the result of a `SELECT * FROM PERSON` with `row.get("birthdate")` fails with:

```
java.lang.NullPointerException: null
	at io.r2dbc.h2.codecs.DateCodec.transform(DateCodec.java:59) ~[r2dbc-h2-0.8.0.M8.jar:na]
	at io.r2dbc.h2.codecs.DateCodec.doDecode(DateCodec.java:44) ~[r2dbc-h2-0.8.0.M8.jar:na]
	at io.r2dbc.h2.codecs.DateCodec.doDecode(DateCodec.java:31) ~[r2dbc-h2-0.8.0.M8.jar:na]
	at io.r2dbc.h2.codecs.AbstractCodec.decode(AbstractCodec.java:60) ~[r2dbc-h2-0.8.0.M8.jar:na]
	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:73) ~[r2dbc-h2-0.8.0.M8.jar:na]
	at io.r2dbc.h2.H2Row.get(H2Row.java:79) ~[r2dbc-h2-0.8.0.M8.jar:na]
	at io.r2dbc.spi.Row.get(Row.java:63) ~[r2dbc-spi-0.8.0.M8.jar:na]
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter$RowParameterValueProvider.getParameterValue(MappingR2dbcConverter.java:426) ~[spring-data-r2dbc-1.0.0.M2.jar:1.0.0.M2]

```

**Comment by pull-vert** [comment]
I have a related issue with java 8 Time types, when calling ```row.get("something")``` with NULL value
```
java.lang.ClassCastException: org.h2.value.ValueNull cannot be cast to org.h2.value.ValueDate
	at org.h2.util.LocalDateTimeUtils.valueToLocalDate(LocalDateTimeUtils.java:325)
	at io.r2dbc.h2.codecs.LocalDateCodec.doDecode(LocalDateCodec.java:22)
	at io.r2dbc.h2.codecs.LocalDateCodec.doDecode(LocalDateCodec.java:9)
```

Same for at least LocalDateTimeCodec, LocalTimeCodec and maybe other java.time.* codecs.

**Comment by matsuyoido** [comment]
I faced the similar issue.

[This code](https://github.com/r2dbc/r2dbc-h2/blob/v0.8.0.M8/src/main/java/io/r2dbc/h2/codecs/AbstractCodec.java#L56-L58) is checking null, but `Value value` is `org.h2.value.ValueNull` .

Forgive me if I'm wrong. I think that `AbstractCodec` should do it as follows.

```java
    public T decode(Value value, Class<? extends T> type) {
        if (value == null || value instanceof ValueNull) {
            return null;
        }
        return doDecode(value, type);
    }
```

The stack trace which I faced is as follows.

```
java.lang.ClassCastException: org.h2.value.ValueNull incompatible with org.h2.value.ValueTimestamp
	at org.h2.util.LocalDateTimeUtils.valueToLocalDateTime(LocalDateTimeUtils.java:361)
	at io.r2dbc.h2.codecs.LocalDateTimeCodec.doDecode(LocalDateTimeCodec.java:22)
	at io.r2dbc.h2.codecs.LocalDateTimeCodec.doDecode(LocalDateTimeCodec.java:9)
	at io.r2dbc.h2.codecs.AbstractCodec.decode(AbstractCodec.java:60)
	at io.r2dbc.h2.codecs.DefaultCodecs.decode(DefaultCodecs.java:73)
	at io.r2dbc.h2.H2Row.get(H2Row.java:79)
	at io.r2dbc.spi.Row.get(Row.java:63)
        ...
```

Version: 0.8.0.M8

**Comment by katzyn** [comment]
The normal check for the `NULL` value in H2 is `value == ValueNull.INSTANCE`. Java's `null` is not a valid `Value` in H2, such additional null check can be useful only if R2DBC has some own way to get `null` here.

**Comment by katzyn** [comment]
`Objects.nonNull(Object)` is not designed for direct invocation, this method should only be used as a method reference `Objects::nonNull` as a better alternative for `t -> t != null`.

BTW, the whole `DateCodec` class looks very suspicious. It works with `java.util.Date`. This data type should be mapped to `TIMESTAMP` data type as required by JDBC specification (and common sense). `java.util.Date` is not a date value, it's a datetime value. To get a `java.util.Date` from H2's non-NULL `Value` code like `new java.util.Date(value.getTimestamp().getTime())` should be used, JSR-310 data types aren't required here.

And I don't see a converter for the normal `java.sql.Date` that is really a date-only value that should be mapped to `DATE` data type.

**Comment by katzyn** [comment]
In JDBC a `java.sql.Date` is returned by default for a `DATE` value in a result set. `java.time.LocalDate` is returned when requested with a modern JDBC drivers.

In Java 8+ libraries it's reasonable to use JSR-310 data types by default. But if R2DCB tries to be more compatible with JDBC a `java.sql.Date` should be used. `java.util.Date` is not expected here.

---

Note that JDBC-compliant drivers return `java.lang.Integer` for `TINYINT` and `SMALLINT` values, but use `java.lang.Byte` and `java.lang.Short` to pass them back to the database. When mappings were defined these data types didn't exist in Java, they were introduced only in Java 1.1, but mappings in JDBC weren't changed, only new mappings from new classes to SQL data types were included (they don't break backward compatibility). I don't think that R2DBC should follow the JDBC here. So hypothetically the R2DBC may update mappings for other data types too.

**Comment by mp911de** [comment]
Thanks for having a look. R2DBC aims for modern data types, so `TIMESTAMP` (Date+time) in [R2DBC should map to `LocalDateTime`](https://r2dbc.io/spec/0.8.0.M8/spec/html/#datatypes.mapping.datetime). A real timestamp (instantaneous point on the time-line) would be rather `Instant`.

We try to avoid exposing `java.util.Date`/`Calendar`/`java.sql.Date`/`java.sql.Timestamp` to provide more application-friendly date types.

@katzyn let us know whether our [R2DBC data type mapping](https://r2dbc.io/spec/0.8.0.M8/spec/html/#datatypes.mapping) makes sense or whether there are things that we should improve.

**Comment by katzyn** [comment]
`BOOLEAN` description probably should not use “bit” term. There are three `BOOLEAN` values in the SQL: `TRUE`, `FALSE`, and `UNKNOWN` (`NULL`). Only some databases need a some numeric data type to represent a boolean value.

`BINARY` / `VARBINARY` is questionable. JDBC uses `byte[]`. I don't think that `ByteBuffer` is more usable here.

`REAL` data type should definitely use `java.lang.Float`.

Where is `DOUBLE PRECISION`?

`FLOAT(n)` in databases that use IEEE data types for it can be mapped to either 32-bit or 64-bit floating point value depending on precision parameter.

JDBC and some databases have `TINYINT` data type that is not listed here, but I see a codec for it.

Some databases (MySQL family and maybe some others) have non-standard unsigned integer data types.

SQL Standard specifies only `TIMESTAMP WITH TIME ZONE`. This data type has only time zone offset, but not the time zone name. Some databases really implement it in such way, some can also hold time zone names (Oracle), some don't preserve any time zone information (PostgreSQL), some don't have such data type at all. Why R2DBC use `TIMESTAMP with Timezone Offset` and `TIMESTAMP with Timezone` names? Second name looks like SQL type name, but it uses a time zone name unlike the SQL type. Perhaps something like `TIMESTAMP with Time Zone` should be used for `OffsetDateTime`. `ZonedDateTime` can also be supported somehow, but it does not have a corresponding SQL data type.

SQL Standard and some databases have `TIME WITH TIME ZONE` (`java.time.OffsetTime`). It looks like nobody knows a valid use case for it, but I think that R2DBC should support it anyway.

Year-month intervals and day-time intervals should be listed separately. They are not compatible. `java.time.Duration` is a reasonable data type for day-time intervals, but for year-months intervals you need to use a `java.time.Period`. This class also has days, unlike year-month intervals. Note that PostgreSQL uses ISO semantics for intervals and it is different from the SQL Standard, it's possible to create a combined year-month-day-time interval in this database that works in very weird way in expressions. SQL Standard is more sane in that area. (PostgreSQL supports the SQL Standard data types too.)

`Object[]` is a reasonable data type for `ARRAY`, but not for `MULTISET`. I think that you need a `java.util.Set` for it. `MULTISET` is an unordered collection in SQL.

JDBC (but not the SQL Standard) has a special type for XML values. Some databases (but not the SQL Standard) have special type(s) for JSON values. In the standard they are data type format clauses and base data type is a some character or binary string data type.

How `DISTINCT` and user-defined data types are represented?

Why precision and scale are mentioned in few data types, but aren't mentioned in other data types that also have parameters?

**Comment by mp911de** [comment]
Thanks a lot. I copied your response into r2dbc/r2dbc-spi#97 to continue in R2DBC SPI with type mapping.

**Comment by gregturn** [comment]
Resolved the focus of this issue (`null` checks and `java.sql.*`/`java.util.*` types) via 6f25812.

As for the other types, they will be tracked in separate issues.
