### ISSUE TITLE
Add disclaimers that this is a bridge over H2 Driver 

### ISSUE THREAD

**Issue by gregturn** [r2dbc/r2dbc-h2#88]
Properly flag the README that this runs over some aspects of JDBC and is not 100% non blocking. 

Instead, the purpose is to support testing and jump starting.

**Comment by katzyn** [comment]
r2dbc-h2 is not actually a bridge over JDBC, it's a bridge over internals of H2 (and they may be changed in every release of H2 in any way).

**Comment by gregturn** [comment]
Granted. I’ll try to make that clear.

**Comment by gregturn** [comment]
@katzyn are you open to a meeting via zoom/Skype/whatever to chat about H2 and r2dbc? You can email me if you wish to continue this chat outside of GitHub.

**Comment by katzyn** [comment]
I don't use Skype and other similar stuff. And I'm not that interested in R2DBC. However, feel free to mention me on GitHub when you need some information about H2.
