### ISSUE TITLE
Pick up known H2 configuration properties

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-h2#92]
H2 support a lot of config options. Instead of being required to specify these via `.option("CIPHER=AES")` and hoping no character harms the URL format, it would make sense to capture these via `ConnectionFactoryOptions` and inspect the R2DBC url for these.

In `H2ConnectionConfiguration`, we should introduce an options map that allows specifying these options. `ConnectionInfo` accepts a `Properties` object that can be used to notify H2 about these options.

See also: http://www.h2database.com/html/features.html#database_url

**Comment by katzyn** [comment]
The more actual and complete documentation for the latest released version is here:
https://h2database.com/javadoc/org/h2/engine/DbSettings.html

However, this list can be modified in each release in any way.

**Comment by katzyn** [comment]
H2 also has a lot of low-level system settings with own documentation, but they affect all databases and can't be modified at runtime, so you can't provide an API for them.

**Comment by mp911de** [comment]
Thanks for your input. I think it is okay to live with the risk that configuration properties may get added/removed/modified in H2. We face the same risk with H2's implementation classes.

For now, I found it's more convenient to specify `r2dbc:h2:…?db_close_delay=-1&db_close_on_exit=false` than the old form `r2dbc:h2:…?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`.

The `options` approach won't go away and users can specify additional options or options that we haven't registered in our code through that mechanism.
